"""
tavern.py — The Multi-NPC Tavern Orchestrator
----------------------------------------------
This module manages a "scene" where multiple NPCs coexist and can interact.

THE CORE IDEA — The Overhear System:
  In a real tavern, conversations aren't private. When Kagetora explains
  the Oni Seals to the player, Silas (across the room) might glance up
  and drop a dry comment. This creates emergent social dynamics between
  NPCs — something no scripted game has ever managed convincingly.

  Every time an NPC responds, there is a REACTION_PROBABILITY (35%) chance
  that one of the OTHER NPCs "overhears" and reacts with 1-2 sentences.
  Their reaction is generated by the same LLM but with a special
  "overheard" prompt that includes what was just said.

ARCHITECT'S NOTE on Conversation History in the Tavern:
  Each NPC maintains its OWN conversation history (what IT said, what the
  player said TO IT). But each NPC also receives a "tavern context" injection
  that summarizes the last few lines of the shared log. This way:
  - Kagetora remembers his OWN relationship with the player
  - But he's also aware that Silas just said something interesting

FUTURE-PROOFING:
  - Phase 5: NPCs can ADDRESS EACH OTHER directly ("@Silas, what do YOU know?")
  - Phase 6: NPCs have goals in the scene (Silas wants to sell something, 
    Kagetora wants the player to leave) — they pursue them autonomously.
  - Phase 7: Export tavern scenes as replay files for game cutscenes.
"""

import random
from dataclasses import dataclass, field
from npc_config import NPC_ROSTER
from engine import NPCForgeEngine
from memory import MemoryManager
from emotion import DEFAULT_EMOTIONS
from npc_config import DEFAULT_MODEL


# ─────────────────────────────────────────────
# DATA STRUCTURES
# ─────────────────────────────────────────────

@dataclass
class TavernMessage:
    """A single message in the shared tavern conversation log."""
    speaker:     str          # NPC name or player name
    npc_key:     str          # NPC roster key (or "player" for player messages)
    text:        str          # The message content
    is_player:   bool = False # True for player messages
    is_reaction: bool = False # True for unrequested NPC reactions (overheard)
    avatar:      str  = "🧑" # Speaker's avatar emoji


# ─────────────────────────────────────────────
# TAVERN SESSION
# ─────────────────────────────────────────────

class TavernSession:
    """
    Manages a multi-NPC conversation scene.

    One TavernSession instance per Streamlit session (stored in session_state).
    It holds the shared log, per-NPC conversation histories, and emotion states.

    Usage:
        tavern = TavernSession(engine, ["⚔️ The Cursed Samurai", "🪙 The Grey Merchant"])
        messages = tavern.run_exchange("@Kagetora: Tell me about the Oni Seals", ...)
    """

    REACTION_PROBABILITY = 0.35  # 35% chance of an NPC overhearing/reacting
    REACTION_MAX_TOKENS  = 120   # Keep reactions brief — they're asides, not speeches
    RECENT_LOG_LINES     = 4     # How many recent log lines to inject as tavern context

    # Patterns for @mention parsing (case-insensitive, partial name match)
    def __init__(
        self,
        engine:      NPCForgeEngine,
        active_keys: list[str],
        player_name: str,
    ):
        """
        Args:
            engine:      Shared NPCForgeEngine instance.
            active_keys: List of NPC roster keys present in this tavern scene.
            player_name: The player's name (for logging).
        """
        self.engine      = engine
        self.active_keys = [k for k in active_keys if k in NPC_ROSTER]
        self.player_name = player_name

        # Shared log — all messages in scene order
        self.log: list[TavernMessage] = []

        # Per-NPC separate conversation histories (for their individual memory)
        self.npc_histories: dict[str, list[dict]] = {k: [] for k in self.active_keys}

        # Per-NPC emotion states (start from initial_emotions in config)
        self.emotion_states: dict[str, dict] = {
            k: dict(NPC_ROSTER[k].get("initial_emotions", DEFAULT_EMOTIONS))
            for k in self.active_keys
        }

        # Per-NPC memory managers (for long-term summary)
        self.memory_managers: dict[str, MemoryManager] = {
            k: MemoryManager(
                groq_client=engine.brain.groq_client,
                model=DEFAULT_MODEL,
                npc_name=NPC_ROSTER[k]["name"],
            )
            for k in self.active_keys
        }

    # ──────────────────────────────────────────
    # Public API
    # ──────────────────────────────────────────

    def run_exchange(
        self,
        player_message: str,
        temperature:    float = 0.85,
    ) -> list[TavernMessage]:
        """
        Process a player message and return all NPC responses generated.

        Steps:
          1. Log the player's message
          2. Identify the target NPC (via @mention or auto-select)
          3. Run that NPC's inference with shared tavern context
          4. Log the response
          5. Roll for a reaction from another NPC
          6. Return all new messages generated this turn

        Args:
            player_message: Raw player text (may contain @NPC_name: prefix).
            temperature:     LLM creativity dial.

        Returns:
            List of TavernMessage objects generated this turn (excludes player msg).
        """
        # 1. Log player message
        player_msg = TavernMessage(
            speaker="player", npc_key="player", text=player_message,
            is_player=True, avatar="🧑"
        )
        self.log.append(player_msg)

        new_messages: list[TavernMessage] = []

        # 2. Parse target NPC
        target_key, clean_message = self._parse_target(player_message)

        # Fall back to NPC with highest curiosity if no explicit target
        if target_key is None:
            target_key = max(
                self.active_keys,
                key=lambda k: self.emotion_states[k].get("curiosity", 5)
            )
            clean_message = player_message

        # 3. Build tavern context for this NPC
        tavern_ctx = self._build_tavern_context(exclude_key=target_key)

        # 4. Get memory context for this NPC
        mem = self.memory_managers[target_key]
        mem.maybe_summarize(self.npc_histories[target_key])
        recent_hist, mem_inject = mem.get_context(self.npc_histories[target_key])

        # 5. Run main inference
        result = self.engine.run_inference(
            npc_key=target_key,
            user_message=clean_message,
            conversation_history=recent_hist,
            emotion_state=self.emotion_states[target_key],
            long_term_summary=mem.long_term_summary,
            temperature=temperature,
            tavern_context=tavern_ctx,
        )

        response_text = result["response"]
        self.emotion_states[target_key] = result["updated_emotion_state"]

        # 6. Update this NPC's conversation history
        self.npc_histories[target_key].append({"role": "user",      "content": clean_message})
        self.npc_histories[target_key].append({"role": "assistant", "content": response_text})

        # 7. Log main response
        target_npc = NPC_ROSTER[target_key]
        main_msg   = TavernMessage(
            speaker=target_npc["name"],
            npc_key=target_key,
            text=response_text,
            avatar=target_npc["avatar"],
        )
        self.log.append(main_msg)
        new_messages.append(main_msg)

        # 8. Roll for NPC reaction (another NPC overhears)
        other_keys = [k for k in self.active_keys if k != target_key]
        if other_keys and random.random() < self.REACTION_PROBABILITY:
            reactor_key = random.choice(other_keys)
            reaction    = self._generate_reaction(
                reactor_key=reactor_key,
                target_npc_name=target_npc["name"],
                player_message=clean_message,
                target_response=response_text,
                temperature=temperature,
            )
            if reaction:
                reactor_npc  = NPC_ROSTER[reactor_key]
                reaction_msg = TavernMessage(
                    speaker=reactor_npc["name"],
                    npc_key=reactor_key,
                    text=reaction,
                    avatar=reactor_npc["avatar"],
                    is_reaction=True,
                )
                self.log.append(reaction_msg)
                new_messages.append(reaction_msg)

        return new_messages

    def run_npc_to_npc_exchange(
        self,
        temperature: float = 0.85,
    ) -> list[TavernMessage]:
        """
        Trigger an autonomous exchange where one NPC addresses another NPC in the scene.
        """
        import random
        if len(self.active_keys) < 2:
            return []
            
        # 1. Pick speaker and target
        speaker_key = random.choice(self.active_keys)
        target_key = random.choice([k for k in self.active_keys if k != speaker_key])
        
        speaker_npc = NPC_ROSTER[speaker_key]
        target_npc = NPC_ROSTER[target_key]
        
        # 2. Build prompt for the speaker to address the target
        recent_log = self._build_tavern_context(exclude_key=speaker_key)
        
        prompt = (
            f"{speaker_npc['system_prompt']}\n\n"
            f"[AUTONOMOUS TAVERN EXCHANGE]\n"
            f"You are sitting in the tavern. You decide to start a conversation with {target_npc['name']}.\n"
            f"Other people present: {self.player_name} (the player).\n"
            f"{recent_log}\n"
            f"Say something directly to {target_npc['name']} (e.g. ask them a question, make a comment about them, or comment on the room's mood).\n"
            f"Address them directly (like '@{target_npc['name'].split()[0]}: ...' or similar in spirit).\n"
            f"Keep it brief (1–3 sentences). Stay in character."
        )
        
        speaker_dialogue = self.engine.brain.think(
            system_prompt=prompt,
            conversation_history=[],
            temperature=temperature,
        )
        
        # Log speaker message
        spk_msg = TavernMessage(
            speaker=speaker_npc["name"],
            npc_key=speaker_key,
            text=speaker_dialogue,
            avatar=speaker_npc["avatar"],
        )
        self.log.append(spk_msg)
        
        # Add to speaker's history
        self.npc_histories[speaker_key].append({"role": "assistant", "content": speaker_dialogue})
        
        # 3. Let the target NPC respond to this message
        target_ctx = self._build_tavern_context(exclude_key=target_key)
        
        target_mem = self.memory_managers[target_key]
        target_mem.maybe_summarize(self.npc_histories[target_key])
        recent_hist, _ = target_mem.get_context(self.npc_histories[target_key])
        
        # Clean target message (remove prefix if speaker used one)
        clean_msg = speaker_dialogue
        prefix_short = f"@{target_npc['name'].split()[0]}:"
        if speaker_dialogue.lower().startswith(prefix_short.lower()):
            clean_msg = speaker_dialogue[len(prefix_short):].strip()
            
        result = self.engine.run_inference(
            npc_key=target_key,
            user_message=f"{speaker_npc['name']}: {clean_msg}",
            conversation_history=recent_hist,
            emotion_state=self.emotion_states[target_key],
            long_term_summary=target_mem.long_term_summary,
            temperature=temperature,
            tavern_context=target_ctx,
        )
        
        target_dialogue = result["response"]
        self.emotion_states[target_key] = result["updated_emotion_state"]
        
        # Add to target's history
        self.npc_histories[target_key].append({"role": "user", "content": f"{speaker_npc['name']}: {clean_msg}"})
        self.npc_histories[target_key].append({"role": "assistant", "content": target_dialogue})
        
        # Log target response
        tgt_msg = TavernMessage(
            speaker=target_npc["name"],
            npc_key=target_key,
            text=target_dialogue,
            avatar=target_npc["avatar"],
        )
        self.log.append(tgt_msg)
        
        return [spk_msg, tgt_msg]

    def get_opening_scene(self, temperature: float = 0.85) -> list[TavernMessage]:
        """
        Generate an opening scene where each NPC introduces themselves
        as the player enters the tavern.

        Called once when the player enters Tavern mode.
        Returns a list of NPC introduction messages.
        """
        intros: list[TavernMessage] = []

        for npc_key in self.active_keys:
            npc = NPC_ROSTER[npc_key]

            scene_prompt = (
                f"{npc['system_prompt']}\n\n"
                f"[TAVERN SCENE OPENING]\n"
                f"You are in a dim, smoky tavern. The player has just walked in.\n"
                f"Others present in the tavern: "
                f"{', '.join(NPC_ROSTER[k]['name'] for k in self.active_keys if k != npc_key)}\n"
                f"Give a short (1-2 sentence) ambient reaction as the player enters. "
                f"You may or may not address them directly — show your personality through the moment."
            )

            intro_text = self.engine.brain.think(
                system_prompt=scene_prompt,
                conversation_history=[],
                temperature=temperature,
            )

            msg = TavernMessage(
                speaker=npc["name"], npc_key=npc_key,
                text=intro_text, avatar=npc["avatar"],
            )
            self.log.append(msg)
            intros.append(msg)

        return intros

    def reset(self):
        """Clear the tavern log and all NPC histories."""
        self.log.clear()
        for key in self.active_keys:
            self.npc_histories[key] = []
            self.emotion_states[key] = dict(
                NPC_ROSTER[key].get("initial_emotions", DEFAULT_EMOTIONS)
            )

    # ──────────────────────────────────────────
    # Private
    # ──────────────────────────────────────────

    def _parse_target(self, message: str) -> tuple[str | None, str]:
        """
        Extract @NPC_name: prefix from player message.

        Matches partial names case-insensitively.
        e.g., "@Kagetora: ..." or "@silas: ..." or "@The Merchant: ..."

        Returns:
            (npc_key, clean_message) or (None, original_message)
        """
        msg_lower = message.lower()
        if not msg_lower.startswith("@"):
            return None, message

        for npc_key in self.active_keys:
            npc_name = NPC_ROSTER[npc_key]["name"].lower()
            prefix   = f"@{npc_name}:"

            if msg_lower.startswith(prefix):
                clean = message[len(prefix):].strip()
                return npc_key, clean

            # Also match first name only (e.g., @silas vs @silas vane)
            first_name = npc_name.split()[0]
            prefix_short = f"@{first_name}:"
            if msg_lower.startswith(prefix_short):
                clean = message[len(prefix_short):].strip()
                return npc_key, clean

        return None, message   # @mention found but didn't match any known NPC

    def _build_tavern_context(self, exclude_key: str) -> str:
        """
        Build the tavern-awareness injection for an NPC.
        Tells the NPC who else is in the room and shows recent scene activity.

        Args:
            exclude_key: The NPC who will receive this context (excluded from
                         the "others present" list to avoid self-reference).
        """
        others = [
            f"{NPC_ROSTER[k]['name']} ({NPC_ROSTER[k]['avatar']})"
            for k in self.active_keys if k != exclude_key
        ]

        # Last N lines of the shared log (excluding player lines for brevity)
        recent_lines = [
            f"{msg.speaker}: {msg.text[:120]}{'...' if len(msg.text) > 120 else ''}"
            for msg in self.log[-self.RECENT_LOG_LINES:]
            if not msg.is_player
        ]

        context = f"\n\n[TAVERN SCENE]\nYou are in a dimly lit tavern."
        if others:
            context += f" Others present: {', '.join(others)}."
        if recent_lines:
            context += f"\nRecent overheard conversation:\n" + "\n".join(recent_lines)
        context += "\n[End tavern context]\n"

        return context

    def _generate_reaction(
        self,
        reactor_key:     str,
        target_npc_name: str,
        player_message:  str,
        target_response: str,
        temperature:     float,
    ) -> str | None:
        """
        Generate a brief "overheard" reaction from a bystander NPC.

        Returns None if the reaction is empty or generation fails.
        """
        reactor_npc    = NPC_ROSTER[reactor_key]
        reactor_emotion = self.emotion_states[reactor_key]
        emo_inject     = self.engine.emotion_engine.to_prompt_injection(
            reactor_emotion, reactor_npc["name"]
        )

        overhear_prompt = (
            f"{reactor_npc['system_prompt']}\n"
            f"{emo_inject}\n"
            f"[TAVERN — OVERHEARD EXCHANGE]\n"
            f"You just overheard this conversation across the tavern:\n"
            f"Player to {target_npc_name}: \"{player_message[:200]}\"\n"
            f"{target_npc_name}: \"{target_response[:200]}\"\n\n"
            f"React with ONE brief aside (1-2 sentences max). "
            f"This is an ambient reaction — you may address the room, mutter to yourself, "
            f"or call out. Show your personality. Do NOT give a long speech."
        )

        try:
            reaction = self.engine.brain.think(
                system_prompt=overhear_prompt,
                conversation_history=[],
                temperature=min(temperature + 0.1, 1.5),
            )
            # Reject suspiciously long reactions
            if len(reaction.split()) > 60:
                reaction = ". ".join(reaction.split(". ")[:2]) + "."
            return reaction.strip() if reaction.strip() else None
        except Exception:
            return None
